import { Header } from '@/components/Header'

import './globals.css'

import type { Metadata } from 'next'
import { Source_Sans_3 } from 'next/font/google'
import localFont from 'next/font/local'
import { Footer } from '@/components/Footer'

const source_sans_pro = Source_Sans_3({ 
  subsets: ['latin'],
  variable: '--font-source',
  weight: ['400', '600', '700']
 })

 export const burbank_condensed = localFont({
  src: '../fonts/Burbank Big Condensed Font.otf',
  variable: '--font-burbank'
})

export const metadata: Metadata = {
  title: 'Desafio Explow',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" className="h-full">
      <body className={`${source_sans_pro.variable} ${burbank_condensed.variable} overflow-x-clip`}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
